name: jupcallers 

on:
  push:
    branches: [ main ]          # ← triggers on every push to main
  schedule:
    - cron: '0 * * * *'  # runs every hr.      
  workflow_dispatch:            # manual button in Actions tab

jobs:
  run:
    runs-on: ubuntu-latest
    environment: secrets
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install more depends
        run: playwright install chromium

      - name: Run jupcaller script
        env:
            SOLANA_PRIVATE_KEY: ${{ secrets.SOLANA_PRIVATE_KEY }}
            JUPITER_API_KEY: ${{ secrets.JUPITER_API_KEY }}
            DEPOSIT_MINT: ${{ secrets.DEPOSIT_MINT }}
        run: python jupcallerbot_signed.py